package com.personal.onmyplate.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4A59A5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDEE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001159)
val md_theme_light_secondary = Color(0xFF5B5D71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDFE1F8)
val md_theme_light_onSecondaryContainer = Color(0xFF181B2B)
val md_theme_light_tertiary = Color(0xFF75546D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD7F2)
val md_theme_light_onTertiaryContainer = Color(0xFF2C1227)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1E)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464E)
val md_theme_light_outline = Color(0xFF76767F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val md_theme_light_inversePrimary = Color(0xFFB9C3FF)
val md_theme_light_surfaceTint = Color(0xFF4A59A5)
val md_theme_light_surfaceTintColor = Color(0xFF4A59A5)

val md_theme_dark_primary = Color(0xFFB9C3FF)
val md_theme_dark_onPrimary = Color(0xFF172874)
val md_theme_dark_primaryContainer = Color(0xFF31408C)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE1FF)
val md_theme_dark_secondary = Color(0xFFC3C5DC)
val md_theme_dark_onSecondary = Color(0xFF2D2F41)
val md_theme_dark_secondaryContainer = Color(0xFF434658)
val md_theme_dark_onSecondaryContainer = Color(0xFFDFE1F8)
val md_theme_dark_tertiary = Color(0xFFE4BAD7)
val md_theme_dark_onTertiary = Color(0xFF43273D)
val md_theme_dark_tertiaryContainer = Color(0xFF5C3D54)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1B1B1E)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1E)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5CF)
val md_theme_dark_outline = Color(0xFF909099)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF303033)
val md_theme_dark_inversePrimary = Color(0xFF4A59A5)
val md_theme_dark_surfaceTint = Color(0xFFB9C3FF)
val md_theme_dark_surfaceTintColor = Color(0xFFB9C3FF)

val seed = Color(0xFF91A0F2)